version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - '5432:5432'
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
