CREATE TABLE IF NOT EXISTS users (
    ID BIGSERIAL NOT NULL,
    Name VARCHAR NOT NULL UNIQUE,
    Password VARCHAR NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS wallets (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    Name VARCHAR NOT NULL UNIQUE,
    OwnerID BIGSERIAL NOT NULL,
    Amount BIGSERIAL NOT NULL,
    FOREIGN KEY (OwnerID) REFERENCES users (ID)
);

INSERT INTO users(Name, Password) 
VALUES('admin','admin') 
ON CONFLICT DO NOTHING;