// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: tictactoe.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestScore) Reset() {
	*x = RequestScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestScore) ProtoMessage() {}

func (x *RequestScore) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestScore.ProtoReflect.Descriptor instead.
func (*RequestScore) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{0}
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{1}
}

func (x *Move) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Move) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Board struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line1 []int64 `protobuf:"zigzag64,1,rep,packed,name=line1,proto3" json:"line1,omitempty"`
	Line2 []int64 `protobuf:"zigzag64,2,rep,packed,name=line2,proto3" json:"line2,omitempty"`
	Line3 []int64 `protobuf:"zigzag64,3,rep,packed,name=line3,proto3" json:"line3,omitempty"`
	// Types that are assignable to Win:
	//	*Board_IsWin
	Win isBoard_Win `protobuf_oneof:"win"`
}

func (x *Board) Reset() {
	*x = Board{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{2}
}

func (x *Board) GetLine1() []int64 {
	if x != nil {
		return x.Line1
	}
	return nil
}

func (x *Board) GetLine2() []int64 {
	if x != nil {
		return x.Line2
	}
	return nil
}

func (x *Board) GetLine3() []int64 {
	if x != nil {
		return x.Line3
	}
	return nil
}

func (m *Board) GetWin() isBoard_Win {
	if m != nil {
		return m.Win
	}
	return nil
}

func (x *Board) GetIsWin() bool {
	if x, ok := x.GetWin().(*Board_IsWin); ok {
		return x.IsWin
	}
	return false
}

type isBoard_Win interface {
	isBoard_Win()
}

type Board_IsWin struct {
	IsWin bool `protobuf:"varint,4,opt,name=is_win,json=isWin,proto3,oneof"`
}

func (*Board_IsWin) isBoard_Win() {}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Reply:
	//	*Status_Board
	//	*Status_Move
	//	*Status_Err
	Reply isStatus_Reply `protobuf_oneof:"reply"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{3}
}

func (m *Status) GetReply() isStatus_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (x *Status) GetBoard() *Board {
	if x, ok := x.GetReply().(*Status_Board); ok {
		return x.Board
	}
	return nil
}

func (x *Status) GetMove() *Move {
	if x, ok := x.GetReply().(*Status_Move); ok {
		return x.Move
	}
	return nil
}

func (x *Status) GetErr() string {
	if x, ok := x.GetReply().(*Status_Err); ok {
		return x.Err
	}
	return ""
}

type isStatus_Reply interface {
	isStatus_Reply()
}

type Status_Board struct {
	Board *Board `protobuf:"bytes,1,opt,name=board,proto3,oneof"`
}

type Status_Move struct {
	Move *Move `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

type Status_Err struct {
	Err string `protobuf:"bytes,3,opt,name=err,proto3,oneof"`
}

func (*Status_Board) isStatus_Reply() {}

func (*Status_Move) isStatus_Reply() {}

func (*Status_Err) isStatus_Reply() {}

type Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandsomeScore int64 `protobuf:"zigzag64,1,opt,name=handsome_score,json=handsomeScore,proto3" json:"handsome_score,omitempty"`
	Super_AIScore int64 `protobuf:"zigzag64,2,opt,name=super_AI_score,json=superAIScore,proto3" json:"super_AI_score,omitempty"`
}

func (x *Score) Reset() {
	*x = Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{4}
}

func (x *Score) GetHandsomeScore() int64 {
	if x != nil {
		return x.HandsomeScore
	}
	return 0
}

func (x *Score) GetSuper_AIScore() int64 {
	if x != nil {
		return x.Super_AIScore
	}
	return 0
}

var File_tictactoe_proto protoreflect.FileDescriptor

var file_tictactoe_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x22, 0x0e, 0x0a, 0x0c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x22, 0x0a, 0x04,
	0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79,
	0x22, 0x69, 0x0a, 0x05, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e,
	0x65, 0x31, 0x18, 0x01, 0x20, 0x03, 0x28, 0x12, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x31, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x32, 0x18, 0x02, 0x20, 0x03, 0x28, 0x12, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x65, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x33, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x12, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x33, 0x12, 0x17, 0x0a, 0x06, 0x69,
	0x73, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x69,
	0x73, 0x57, 0x69, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x22, 0x76, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65,
	0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12,
	0x25, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x48, 0x00,
	0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x54, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x68, 0x61, 0x6e, 0x64, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x12, 0x52, 0x0d, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x6f, 0x6d, 0x65, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x75, 0x70, 0x65, 0x72, 0x5f, 0x41, 0x49, 0x5f,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x12, 0x52, 0x0c, 0x73, 0x75, 0x70,
	0x65, 0x72, 0x41, 0x49, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x7f, 0x0a, 0x0f, 0x54, 0x69, 0x63,
	0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x41, 0x49, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x17, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61,
	0x63, 0x74, 0x6f, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x1a, 0x10, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x12, 0x11, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x1a, 0x11, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x3b, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tictactoe_proto_rawDescOnce sync.Once
	file_tictactoe_proto_rawDescData = file_tictactoe_proto_rawDesc
)

func file_tictactoe_proto_rawDescGZIP() []byte {
	file_tictactoe_proto_rawDescOnce.Do(func() {
		file_tictactoe_proto_rawDescData = protoimpl.X.CompressGZIP(file_tictactoe_proto_rawDescData)
	})
	return file_tictactoe_proto_rawDescData
}

var file_tictactoe_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tictactoe_proto_goTypes = []interface{}{
	(*RequestScore)(nil), // 0: tictactoe.RequestScore
	(*Move)(nil),         // 1: tictactoe.Move
	(*Board)(nil),        // 2: tictactoe.Board
	(*Status)(nil),       // 3: tictactoe.Status
	(*Score)(nil),        // 4: tictactoe.Score
}
var file_tictactoe_proto_depIdxs = []int32{
	2, // 0: tictactoe.Status.board:type_name -> tictactoe.Board
	1, // 1: tictactoe.Status.move:type_name -> tictactoe.Move
	0, // 2: tictactoe.TictactoeAIGame.GetScore:input_type -> tictactoe.RequestScore
	3, // 3: tictactoe.TictactoeAIGame.StartGame:input_type -> tictactoe.Status
	4, // 4: tictactoe.TictactoeAIGame.GetScore:output_type -> tictactoe.Score
	3, // 5: tictactoe.TictactoeAIGame.StartGame:output_type -> tictactoe.Status
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tictactoe_proto_init() }
func file_tictactoe_proto_init() {
	if File_tictactoe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tictactoe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tictactoe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tictactoe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Board); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tictactoe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tictactoe_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tictactoe_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Board_IsWin)(nil),
	}
	file_tictactoe_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Status_Board)(nil),
		(*Status_Move)(nil),
		(*Status_Err)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tictactoe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tictactoe_proto_goTypes,
		DependencyIndexes: file_tictactoe_proto_depIdxs,
		MessageInfos:      file_tictactoe_proto_msgTypes,
	}.Build()
	File_tictactoe_proto = out.File
	file_tictactoe_proto_rawDesc = nil
	file_tictactoe_proto_goTypes = nil
	file_tictactoe_proto_depIdxs = nil
}
